## Polynomial Terms

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import statsmodels.api as sm

In [2]:
insurance_df = pd.read_csv('Data/insurance.csv')
insurance_df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [18]:
insurance_df.corr(numeric_only=True)

,age,bmi,children,charges,smoker_flag,age_sq,age_3,age_4
age,1.000000,0.109272,0.042469,0.299008,-0.025019,0.988380,0.959865,0.923337
bmi,0.109272,1.000000,0.012759,0.198341,0.003750,0.112804,0.113443,0.112234
children,0.042469,0.012759,1.000000,0.067998,0.007673,-0.003259,-0.041494,-0.070827
charges,0.299008,0.198341,0.067998,1.000000,0.787251,0.300772,0.297167,0.290581
smoker_flag,-0.025019,0.003750,0.007673,0.787251,1.000000,-0.026120,-0.025790,-0.024248
age_sq,0.988380,0.112804,-0.003259,0.300772,-0.026120,1.000000,0.991134,0.969947
age_3,0.959865,0.113443,-0.041494,0.297167,-0.025790,0.991134,1.000000,0.993540
age_4,0.923337,0.112234,-0.070827,0.290581,-0.024248,0.969947,0.993540,1.000000

In [15]:
from sklearn.model_selection import train_test_split

insurance_df['smoker_flag'] = np.where(insurance_df['smoker'] == 'yes', 1, 0)
insurance_df['age_sq'] = insurance_df['age'] **2
insurance_df['age_3']  = insurance_df['age'] **3
insurance_df['age_4']  = insurance_df['age'] **4

features = [
    "age",
    "age_sq",
    #"age_3",
    #"age_4",
    "bmi",
    "children",
    "smoker_flag"
]

X = sm.add_constant(insurance_df[features])
y = insurance_df["charges"]

X, X_test, y, y_test = train_test_split(X, y, test_size=0.2, random_state=2023)

In [16]:
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score as r2
from sklearn.metrics import mean_absolute_error as mae

kf = KFold(n_splits=5, shuffle=True, random_state=2023)

# Create a list to store validation scores for each fold
cv_lm_r2s = []
cv_lm_mae = []

# Loop through each fold in X and y
for train_ind, val_ind in kf.split(X, y):
    #Subset data based on CV folds
    X_train, y_train = X.iloc[train_ind], y.iloc[train_ind]
    X_val, y_val = X.iloc[val_ind], y.iloc[val_ind]

    # Fit the model on fold's training data
    model = sm.OLS(y_train, X_train).fit()

    # Append Validation score to list
    cv_lm_r2s.append(r2(y_val, model.predict(X_val),))
    cv_lm_mae.append(mae(y_val, model.predict(X_val),))

print("All Validation R2s: ", [round(x,3) for x in cv_lm_r2s])
print(f"Cross Val R2s: {round(np.mean(cv_lm_r2s), 3)} +- {round(np.std(cv_lm_r2s), 3)}")

print("All Validation MAEs: ", [round(x, 3) for x in cv_lm_mae])
print(f"Cross Val MAEs: {round(np.mean(cv_lm_mae), 3)} +- {round(np.std(cv_lm_mae), 3)}")

All Validation R2s:  [0.739, 0.756, 0.756, 0.775, 0.716]
Cross Val R2s: 0.748 +- 0.02
All Validation MAEs:  [4352.476, 3921.623, 4365.72, 3881.476, 4363.935]
Cross Val MAEs: 4177.046 +- 225.346

## Combining Features

In [17]:
insurance_df.corr(numeric_only=True)

,age,bmi,children,charges,smoker_flag,age_sq,age_3,age_4
age,1.000000,0.109272,0.042469,0.299008,-0.025019,0.988380,0.959865,0.923337
bmi,0.109272,1.000000,0.012759,0.198341,0.003750,0.112804,0.113443,0.112234
children,0.042469,0.012759,1.000000,0.067998,0.007673,-0.003259,-0.041494,-0.070827
charges,0.299008,0.198341,0.067998,1.000000,0.787251,0.300772,0.297167,0.290581
smoker_flag,-0.025019,0.003750,0.007673,0.787251,1.000000,-0.026120,-0.025790,-0.024248
age_sq,0.988380,0.112804,-0.003259,0.300772,-0.026120,1.000000,0.991134,0.969947
age_3,0.959865,0.113443,-0.041494,0.297167,-0.025790,0.991134,1.000000,0.993540
age_4,0.923337,0.112234,-0.070827,0.290581,-0.024248,0.969947,0.993540,1.000000

In [20]:
from sklearn.model_selection import train_test_split

insurance_df = insurance_df.assign(
    smoker_flag = np.where(insurance_df["smoker"] == 'yes', 1, 0),
    age_sq = insurance_df["age"] **2,
    age_bmi_sum = insurance_df["age"] + insurance_df["bmi"]
)

features = [
    #"age",
    #"age_sq",
    #"bmi",
    "children",
    "smoker_flag",
    "age_bmi_sum"
]

X = sm.add_constant(insurance_df[features])
y = insurance_df["charges"]

X, X_test, y, y_test = train_test_split(X, y, test_size=0.2, random_state=2023)

In [21]:
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score as r2
from sklearn.metrics import mean_absolute_error as mae

kf = KFold(n_splits=5, shuffle=True, random_state=2023)

# Create a list to store validation scores for each fold
cv_lm_r2s = []
cv_lm_mae = []

# Loop through each fold in X and y
for train_ind, val_ind in kf.split(X, y):
    #Subset data based on CV folds
    X_train, y_train = X.iloc[train_ind], y.iloc[train_ind]
    X_val, y_val = X.iloc[val_ind], y.iloc[val_ind]

    # Fit the model on fold's training data
    model = sm.OLS(y_train, X_train).fit()

    # Append Validation score to list
    cv_lm_r2s.append(r2(y_val, model.predict(X_val),))
    cv_lm_mae.append(mae(y_val, model.predict(X_val),))

print("All Validation R2s: ", [round(x,3) for x in cv_lm_r2s])
print(f"Cross Val R2s: {round(np.mean(cv_lm_r2s), 3)} +- {round(np.std(cv_lm_r2s), 3)}")

print("All Validation MAEs: ", [round(x, 3) for x in cv_lm_mae])
print(f"Cross Val MAEs: {round(np.mean(cv_lm_mae), 3)} +- {round(np.std(cv_lm_mae), 3)}")

All Validation R2s:  [0.737, 0.751, 0.755, 0.771, 0.713]
Cross Val R2s: 0.746 +- 0.02
All Validation MAEs:  [4262.086, 3934.033, 4373.104, 3863.039, 4358.212]
Cross Val MAEs: 4158.095 +- 216.496

In [ ]:
model = sm.OLS(y, X).fit()

print(f"Test R2: {r2(y_test, model.predict(X_test))}")
print(f"Test MAE: {mae(y_test, model.predict(X_test))}")

In [ ]:
model.summary()